CREATE DATABASE IF NOT EXISTS `Newark IT store`;
USE `Newark IT store`;

CUSTOMER:
CREATE TABLE Customer (
  CID INT PRIMARY KEY,
  FName VARCHAR(50)    NOT NULL,
  LName VARCHAR(50)    NOT NULL,
  Email VARCHAR(100)   NOT NULL UNIQUE,
  Address VARCHAR(255) NOT NULL,
  Phone VARCHAR(20)    NOT NULL,
  Status ENUM('regular','silver','gold','platinum') NOT NULL
);

CREDIT_CARD:
CREATE TABLE Credit_Card (
  CCNumber VARCHAR(16) PRIMARY KEY,
  SecNumber CHAR(4)         NOT NULL,
  OwnerName VARCHAR(100)    NOT NULL,
  CCType VARCHAR(20)        NOT NULL,
  BillingAddress VARCHAR(255) NOT NULL,
  ExpDate DATE              NOT NULL,
  StoredCardCID INT         NULL,
  FOREIGN KEY (StoredCardCID)
    REFERENCES Customer(CID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

 SHIPPING_ADDRESS
CREATE TABLE Shipping_Address (
  CID INT               NOT NULL,
  SAName VARCHAR(50)    NOT NULL,
  Street VARCHAR(100)   NOT NULL,
  SNumber VARCHAR(20)   NOT NULL,
  City VARCHAR(50)      NOT NULL,
  Zip VARCHAR(10)       NOT NULL,
  State VARCHAR(50)     NOT NULL,
  Country VARCHAR(50)   NOT NULL,
  RecepientName VARCHAR(100) NOT NULL,
  PRIMARY KEY (CID, SAName),
  FOREIGN KEY (CID)
    REFERENCES Customer(CID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

SILVER_AND_ABOVE
CREATE TABLE Silver_And_Above (
  CID INT PRIMARY KEY,
  CreditLine DECIMAL(10,2) NOT NULL,
  FOREIGN KEY (CID)
    REFERENCES Customer(CID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

PRODUCT
CREATE TABLE Product (
  PID INT PRIMARY KEY,
  PName VARCHAR(100) NOT NULL,
  PPrice DECIMAL(10,2) NOT NULL,
  PDescription TEXT,
  PType VARCHAR(50) NOT NULL,
  PQuantity INT NOT NULL
);

OFFER_PRODUCT
CREATE TABLE Offer_Product (
  PID INT PRIMARY KEY,
  OfferPrice DECIMAL(10,2) NOT NULL,
  FOREIGN KEY (PID)
    REFERENCES Product(PID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

 COMPUTER
CREATE TABLE Computer (
  PID INT PRIMARY KEY,
  CPUType VARCHAR(50) NOT NULL,
  FOREIGN KEY (PID)
    REFERENCES Product(PID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

 LAPTOP
CREATE TABLE Laptop (
  PID INT PRIMARY KEY,
  BType VARCHAR(50)    NOT NULL,
  Weight DECIMAL(5,2)  NOT NULL,
  FOREIGN KEY (PID)
    REFERENCES Product(PID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

PRINTER
CREATE TABLE Printer (
  PID INT PRIMARY KEY,
  PrinterType VARCHAR(50) NOT NULL,
  Resolution VARCHAR(20)    NOT NULL,
  FOREIGN KEY (PID)
    REFERENCES Product(PID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

 BASKET
CREATE TABLE Basket (
  BID INT PRIMARY KEY,
  CID INT NOT NULL,
  FOREIGN KEY (CID)
    REFERENCES Customer(CID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

APPEARS_IN
CREATE TABLE Appears_In (
  BID INT      NOT NULL,
  PID INT      NOT NULL,
  Quantity INT NOT NULL,
  PriceSold DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (BID, PID),
  FOREIGN KEY (BID)
    REFERENCES Basket(BID)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  FOREIGN KEY (PID)
    REFERENCES Product(PID)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);

 TRANSACTION
CREATE TABLE `Transaction` (
  BID INT         NOT NULL,
  CID INT         NOT NULL,
  SAName VARCHAR(50) NOT NULL,
  CCNumber VARCHAR(16) NOT NULL,
  TDate DATETIME  NOT NULL DEFAULT CURRENT_TIMESTAMP,
  TTag ENUM('delivered','not-delivered') NOT NULL DEFAULT 'delivered',
  PRIMARY KEY (BID),
  FOREIGN KEY (BID)
    REFERENCES Basket(BID)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  FOREIGN KEY (CID)
    REFERENCES Customer(CID)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  FOREIGN KEY (CCNumber)
    REFERENCES Credit_Card(CCNumber)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  FOREIGN KEY (CID, SAName)
    REFERENCES Shipping_appears_inbasketAddress(CID, SAName)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);
